# Generated by Django 5.0.4 on 2025-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoResumeProxy',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mongo Resume',
                'verbose_name_plural': 'Mongo Resumes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('required_skills', models.TextField(blank=True)),
                ('required_experience', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
    ]
